'use strict';

exports.seed = function(knex) {
  return knex('projects').del()
    .then(() => {
      return knex('projects').insert([{
        id: 1,
        user_id: 1,
        title: 'An App for Dog Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/1173/animal-dog-pet-cute.jpg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 3,
      },
      {
        id: 2,
        user_id: 1,
        title: 'An App for Cat Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/96938/pexels-photo-96938.jpeg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 1,
      },
      {
        id: 3,
        user_id: 1,
        title: 'An App for Dog Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/1173/animal-dog-pet-cute.jpg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 3,
      },
      {
        id: 4,
        user_id: 1,
        title: 'An App for Cat Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/96938/pexels-photo-96938.jpeg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 1,
      },
      {
        id: 5,
        user_id: 1,
        title: 'An App for Dog Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/1173/animal-dog-pet-cute.jpg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 3,
      },
      {
        id: 6,
        user_id: 1,
        title: 'An App for Cat Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/96938/pexels-photo-96938.jpeg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 1,
      },
      {
        id: 7,
        user_id: 1,
        title: 'An App for Dog Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/1173/animal-dog-pet-cute.jpg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 3,
      },
      {
        id: 8,
        user_id: 1,
        title: 'An App for Cat Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/96938/pexels-photo-96938.jpeg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 1,
      },
      {
        id: 9,
        user_id: 1,
        title: 'An App for Dog Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/1173/animal-dog-pet-cute.jpg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 3,
      },
      {
        id: 10,
        user_id: 1,
        title: 'An App for Cat Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/96938/pexels-photo-96938.jpeg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 1,
      },
      {
        id: 11,
        user_id: 1,
        title: 'An App for Dog Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/1173/animal-dog-pet-cute.jpg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 3,
      },
      {
        id: 12,
        user_id: 1,
        title: 'An App for Cat Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/96938/pexels-photo-96938.jpeg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 1,
      },
      {
        id: 13,
        user_id: 1,
        title: 'An App for Dog Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/1173/animal-dog-pet-cute.jpg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 3,
      },
      {
        id: 14,
        user_id: 1,
        title: 'An App for Cat Lovers',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        img_url: 'https://static.pexels.com/photos/96938/pexels-photo-96938.jpeg',
        web_url: 'https://www.seattle.gov/animal-shelter/adopt/applications',
        github_link: 'https://github.com/',
        likes: 1,
      }
    ])
    })
    .then(function() {
      return knex.raw("SELECT setval('projects_id_seq', (SELECT MAX(id) FROM projects));");
    });
};
